### ISSUE TITLE
ShowDirective.txt

### ISSUE THREAD

**Issue by BFallert** [uleodolter/primo-new-ui-hackathon#1]
I have add the content in showDirectives.txt as a bookmark. However only one "hover for id" is showed. May I know the reason?

I copy this question from  rurikayuki in
https://github.com/ExLibrisGroup/primo-explore-package/issues/8

see there!

**Comment by uleodolter** [comment]
updated showDirectives.txt bookmark to latest version of primo-explore-package.
thanks @BFallert
